/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as Hero1RouteImport } from './routes/hero-1'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PrivateLabelRouteImport } from './routes/private-label'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as VirtualTourRouteImport } from './routes/virtual-tour'
import { Route as WhyRouteImport } from './routes/why'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAuthenticatedRouteRouteImport } from './routes/app/_authenticated/route'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AppAuthenticatedEnquiriesRouteImport } from './routes/app/_authenticated/enquiries'
import { Route as AppAuthenticatedPostsIndexRouteImport } from './routes/app/_authenticated/posts/index'
import { Route as AppAuthenticatedPostsPostIdRouteImport } from './routes/app/_authenticated/posts/$postId'
import { Route as AppAuthenticatedPostsNewRouteImport } from './routes/app/_authenticated/posts/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const Hero1Route = Hero1RouteImport.update({
  id: '/hero-1',
  path: '/hero-1',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLabelRoute = PrivateLabelRouteImport.update({
  id: '/private-label',
  path: '/private-label',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualTourRoute = VirtualTourRouteImport.update({
  id: '/virtual-tour',
  path: '/virtual-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthenticatedRouteRoute = AppAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedEnquiriesRoute =
  AppAuthenticatedEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedPostsIndexRoute =
  AppAuthenticatedPostsIndexRouteImport.update({
    id: '/posts/',
    path: '/posts/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedPostsPostIdRoute =
  AppAuthenticatedPostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedPostsNewRoute =
  AppAuthenticatedPostsNewRouteImport.update({
    id: '/posts/new',
    path: '/posts/new',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/campus': typeof CampusRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/facilities': typeof FacilitiesRoute
  '/hero-1': typeof Hero1Route
  '/investors': typeof InvestorsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/private-label': typeof PrivateLabelRoute
  '/products': typeof ProductsRoute
  '/virtual-tour': typeof VirtualTourRoute
  '/why': typeof WhyRoute
  '/app/login': typeof AppLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/app/enquiries': typeof AppAuthenticatedEnquiriesRoute
  '/app/posts/$postId': typeof AppAuthenticatedPostsPostIdRoute
  '/app/posts/new': typeof AppAuthenticatedPostsNewRoute
  '/app/posts/': typeof AppAuthenticatedPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/campus': typeof CampusRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/facilities': typeof FacilitiesRoute
  '/hero-1': typeof Hero1Route
  '/investors': typeof InvestorsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/private-label': typeof PrivateLabelRoute
  '/products': typeof ProductsRoute
  '/virtual-tour': typeof VirtualTourRoute
  '/why': typeof WhyRoute
  '/app': typeof AppIndexRoute
  '/app/login': typeof AppLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/app/enquiries': typeof AppAuthenticatedEnquiriesRoute
  '/app/posts/$postId': typeof AppAuthenticatedPostsPostIdRoute
  '/app/posts/new': typeof AppAuthenticatedPostsNewRoute
  '/app/posts': typeof AppAuthenticatedPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/campus': typeof CampusRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/facilities': typeof FacilitiesRoute
  '/hero-1': typeof Hero1Route
  '/investors': typeof InvestorsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/private-label': typeof PrivateLabelRoute
  '/products': typeof ProductsRoute
  '/virtual-tour': typeof VirtualTourRoute
  '/why': typeof WhyRoute
  '/app/_authenticated': typeof AppAuthenticatedRouteRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/app/_authenticated/enquiries': typeof AppAuthenticatedEnquiriesRoute
  '/app/_authenticated/posts/$postId': typeof AppAuthenticatedPostsPostIdRoute
  '/app/_authenticated/posts/new': typeof AppAuthenticatedPostsNewRoute
  '/app/_authenticated/posts/': typeof AppAuthenticatedPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/about'
    | '/campus'
    | '/careers'
    | '/contact'
    | '/design-system'
    | '/facilities'
    | '/hero-1'
    | '/investors'
    | '/opportunities'
    | '/private-label'
    | '/products'
    | '/virtual-tour'
    | '/why'
    | '/app/login'
    | '/blog/$slug'
    | '/app/'
    | '/blog/'
    | '/app/enquiries'
    | '/app/posts/$postId'
    | '/app/posts/new'
    | '/app/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/campus'
    | '/careers'
    | '/contact'
    | '/design-system'
    | '/facilities'
    | '/hero-1'
    | '/investors'
    | '/opportunities'
    | '/private-label'
    | '/products'
    | '/virtual-tour'
    | '/why'
    | '/app'
    | '/app/login'
    | '/blog/$slug'
    | '/blog'
    | '/app/enquiries'
    | '/app/posts/$postId'
    | '/app/posts/new'
    | '/app/posts'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/about'
    | '/campus'
    | '/careers'
    | '/contact'
    | '/design-system'
    | '/facilities'
    | '/hero-1'
    | '/investors'
    | '/opportunities'
    | '/private-label'
    | '/products'
    | '/virtual-tour'
    | '/why'
    | '/app/_authenticated'
    | '/app/login'
    | '/blog/$slug'
    | '/app/'
    | '/blog/'
    | '/app/_authenticated/enquiries'
    | '/app/_authenticated/posts/$postId'
    | '/app/_authenticated/posts/new'
    | '/app/_authenticated/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CampusRoute: typeof CampusRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DesignSystemRoute: typeof DesignSystemRoute
  FacilitiesRoute: typeof FacilitiesRoute
  Hero1Route: typeof Hero1Route
  InvestorsRoute: typeof InvestorsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PrivateLabelRoute: typeof PrivateLabelRoute
  ProductsRoute: typeof ProductsRoute
  VirtualTourRoute: typeof VirtualTourRoute
  WhyRoute: typeof WhyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-1': {
      id: '/hero-1'
      path: '/hero-1'
      fullPath: '/hero-1'
      preLoaderRoute: typeof Hero1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-label': {
      id: '/private-label'
      path: '/private-label'
      fullPath: '/private-label'
      preLoaderRoute: typeof PrivateLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-tour': {
      id: '/virtual-tour'
      path: '/virtual-tour'
      fullPath: '/virtual-tour'
      preLoaderRoute: typeof VirtualTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_authenticated': {
      id: '/app/_authenticated'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated/enquiries': {
      id: '/app/_authenticated/enquiries'
      path: '/enquiries'
      fullPath: '/app/enquiries'
      preLoaderRoute: typeof AppAuthenticatedEnquiriesRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/posts/': {
      id: '/app/_authenticated/posts/'
      path: '/posts'
      fullPath: '/app/posts/'
      preLoaderRoute: typeof AppAuthenticatedPostsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/posts/$postId': {
      id: '/app/_authenticated/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/app/posts/$postId'
      preLoaderRoute: typeof AppAuthenticatedPostsPostIdRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/posts/new': {
      id: '/app/_authenticated/posts/new'
      path: '/posts/new'
      fullPath: '/app/posts/new'
      preLoaderRoute: typeof AppAuthenticatedPostsNewRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
  }
}

interface AppAuthenticatedRouteRouteChildren {
  AppAuthenticatedEnquiriesRoute: typeof AppAuthenticatedEnquiriesRoute
  AppAuthenticatedPostsPostIdRoute: typeof AppAuthenticatedPostsPostIdRoute
  AppAuthenticatedPostsNewRoute: typeof AppAuthenticatedPostsNewRoute
  AppAuthenticatedPostsIndexRoute: typeof AppAuthenticatedPostsIndexRoute
}

const AppAuthenticatedRouteRouteChildren: AppAuthenticatedRouteRouteChildren = {
  AppAuthenticatedEnquiriesRoute: AppAuthenticatedEnquiriesRoute,
  AppAuthenticatedPostsPostIdRoute: AppAuthenticatedPostsPostIdRoute,
  AppAuthenticatedPostsNewRoute: AppAuthenticatedPostsNewRoute,
  AppAuthenticatedPostsIndexRoute: AppAuthenticatedPostsIndexRoute,
}

const AppAuthenticatedRouteRouteWithChildren =
  AppAuthenticatedRouteRoute._addFileChildren(
    AppAuthenticatedRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppAuthenticatedRouteRoute: typeof AppAuthenticatedRouteRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthenticatedRouteRoute: AppAuthenticatedRouteRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CampusRoute: CampusRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DesignSystemRoute: DesignSystemRoute,
  FacilitiesRoute: FacilitiesRoute,
  Hero1Route: Hero1Route,
  InvestorsRoute: InvestorsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PrivateLabelRoute: PrivateLabelRoute,
  ProductsRoute: ProductsRoute,
  VirtualTourRoute: VirtualTourRoute,
  WhyRoute: WhyRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
