import type { EnquiryRecord } from "./types"

function daysAgo(days: number, hour = 10): string {
  const date = new Date()
  date.setDate(date.getDate() - days)
  date.setHours(hour, 0, 0, 0)
  return date.toISOString()
}

export const seedEnquiries: EnquiryRecord[] = [
  {
    id: "seed-001",
    name: "Rajesh Verma",
    company: "Verma Agro Foods Pvt Ltd",
    phone: "+91 98230 44112",
    email: "rajesh.verma@vermaagro.in",
    interest: "plot",
    message:
      "Looking for a 2-acre developed plot for a spice processing unit. Target throughput 8 MT/day. Need utility connections confirmed.",
    createdAt: daysAgo(1, 9),
    status: "new",
    source: "contact",
  },
  {
    id: "seed-002",
    name: "Priya Nair",
    company: "Coastal Cold Chain LLP",
    phone: "+91 98470 22331",
    email: "priya@coastalcold.in",
    interest: "facility",
    message:
      "Interested in shared IQF line capacity for frozen mango pulp. Seasonal run — April to July.",
    createdAt: daysAgo(2, 14),
    status: "contacted",
    source: "landing",
    notes: "Called back — sending rate card for IQF slot booking.",
  },
  {
    id: "seed-003",
    name: "Amit Khare",
    company: "Khare MSME Foods",
    phone: "+91 87700 55678",
    email: "amit.khare@gmail.com",
    interest: "msme",
    message: "Need a plug-and-play shed for namkeen manufacturing. 1,500 sq ft minimum.",
    createdAt: daysAgo(3, 11),
    status: "qualified",
    source: "contact",
    notes: "Site visit scheduled for next Tuesday.",
  },
  {
    id: "seed-004",
    name: "Sunita Devi",
    company: "Bastar Organic Collective",
    phone: "+91 94060 88901",
    email: "sunita@bastarorganic.org",
    interest: "plot",
    message:
      "Farmer producer organisation exploring a small processing unit for mahua and tamarind products.",
    createdAt: daysAgo(4, 16),
    status: "new",
    source: "landing",
  },
  {
    id: "seed-005",
    name: "Vikram Singh",
    company: "Singh Capital Partners",
    phone: "+91 98110 33445",
    email: "vikram@singhcap.in",
    interest: "jv",
    message:
      "Exploring joint venture for a 5,000 MT cold storage expansion. Happy to share our portfolio and capital commitment.",
    createdAt: daysAgo(5, 10),
    status: "contacted",
    source: "contact",
  },
  {
    id: "seed-006",
    name: "Meena Patel",
    company: "Patel Snacks & Beverages",
    phone: "+91 97250 66789",
    email: "meena@patelsnacks.com",
    interest: "msme",
    message: "Existing brand looking to relocate from rented facility in Raipur. Need shed with power backup.",
    createdAt: daysAgo(7, 13),
    status: "closed",
    source: "contact",
    notes: "Chose a competitor park — budget constraints.",
  },
  {
    id: "seed-007",
    name: "Arjun Mehta",
    company: "",
    phone: "+91 99887 11223",
    email: "arjun.mehta@outlook.com",
    interest: "other",
    message: "Please share the current rate card for all plot sizes and MSME sheds.",
    createdAt: daysAgo(8, 8),
    status: "contacted",
    source: "landing",
  },
  {
    id: "seed-008",
    name: "Deepak Rao",
    company: "Rao Exports International",
    phone: "+91 94480 99001",
    email: "deepak@raoexports.com",
    interest: "facility",
    message:
      "Aseptic line enquiry for mango concentrate export to Middle East. Need FSSAI and export documentation support details.",
    createdAt: daysAgo(10, 15),
    status: "qualified",
    source: "contact",
    notes: "Technical team to share aseptic specs and MOQ.",
  },
  {
    id: "seed-009",
    name: "Kavita Sharma",
    company: "Sharma Dairy Products",
    phone: "+91 98765 43210",
    email: "kavita@sharmadairy.in",
    interest: "plot",
    message: "1-acre plot for dairy processing — paneer and ghee unit. Need water and effluent details.",
    createdAt: daysAgo(12, 9),
    status: "new",
    source: "contact",
  },
  {
    id: "seed-010",
    name: "Rohit Agarwal",
    company: "Agarwal Grain Mills",
    phone: "+91 93000 77889",
    email: "rohit@agarwalgrains.com",
    interest: "facility",
    message: "Dry warehouse capacity enquiry — 500 MT for 6 months. Pulses and rice storage.",
    createdAt: daysAgo(14, 11),
    status: "closed",
    source: "landing",
    notes: "Converted — warehouse lease signed.",
  },
]
